codecov:
  disable_default_path_fixes: true

fixes:
   - "/github/workspace/core/::"

coverage:
  status:
    patch:
      default:
        target: 0%
    project:
      default:
        target: 50%
        threshold: 1%
